### ISSUE TITLE
Typo #02 in project "Build an interactive soundoard with p5js"

### ISSUE THREAD

**Issue by MilanGrujicic** [codedex-io/projects#100]
Hello team,

I would like to report a typo in this [project](https://www.codedex.io/projects/build-an-interactive-soundboard-with-p5js).

Replace "position" with "positions", the explanation is:

`There are many prepositions that refer to direction, time, positioning, location, and more, but they are not all interchangeable.`

See attached picture for more context. 👇
![typosoundboardproject02](https://github.com/codedex-io/projects/assets/48260426/2b952581-fba2-40ea-9116-4df19c86b369)

**Comment by sonnynomnom** [comment]
Hi Milan, I think this is actually fine because of the "ratios" plural. Because this is intentional, I will give it a +0 here and backlogging this. Closing!
