### ISSUE TITLE
Typo in project "Build a Pomodoro App with HTML, CSS, JavaScript"

### ISSUE THREAD

**Issue by MilanGrujicic** [codedex-io/projects#106]
Hello team,

I would like to report a typo in this [project](https://www.codedex.io/projects/build-a-pomodoro-app-with-html-css-js).

Replace 'It is made of two semi-circles for the left-side and right-side' with 'It is made of two semi-circles on the left-side and right-side'.

See attached picture for more context. 👇
![typo01pomodoro](https://github.com/codedex-io/projects/assets/48260426/27bf73fb-d7ef-476c-923a-78f6afb191fc)

**Comment by sonnynomnom** [comment]
Closing! Not deducting points for this one.
