### ISSUE TITLE
Typo in project "Build a Discord Bot with Python"

### ISSUE THREAD

**Issue by MilanGrujicic** [codedex-io/projects#109]
Hello team,

I would like to report a typo in this [project](https://www.codedex.io/projects/build-a-discord-bot-with-python).

Replace 'explicity' with 'explicitly'.

See attached picture for more context. 👇
![discordTypoProject](https://github.com/codedex-io/projects/assets/48260426/98b51ca2-bfdc-415d-8f08-4f988e08d1c9)

**Comment by sonnynomnom** [comment]
Closing! +4'ed.
