### ISSUE TITLE
Typo in project Build Pong with PyGame

### ISSUE THREAD

**Issue by MilanGrujicic** [codedex-io/projects#110]
Hello team,

I would like to report a typo in this [project](https://www.codedex.io/projects/build-pong-with-pygame).

The string 'wheter' could be replaced with 'whether' in order to give more credibility by respecting the correct spelling of the word 'whether'.

Please see picture below for more context. 👇
![pongtypo](https://github.com/codedex-io/projects/assets/48260426/a34245a1-c14b-4df2-85c7-6db497ed7e30)

**Comment by sonnynomnom** [comment]
Closing! +2 for the bug flag! Replying in the comment~
