### ISSUE TITLE
Typo #01 in project Detect "Not Hot Dogs" with hugging face API

### ISSUE THREAD

**Issue by MilanGrujicic** [codedex-io/projects#111]
Hello team,

I would like to report a typo in this [project](https://www.codedex.io/projects/detect-hotdog-with-hugging-face).

The strings 'packlage' should be replaced with 'package'.

See image below for context. 👇

![typo01hotdog](https://github.com/codedex-io/projects/assets/48260426/146d2668-2950-428e-98ee-4842cb29dd98)

**Comment by sonnynomnom** [comment]
Fixed and closing the issue!
