### ISSUE TITLE
Project Tutorial Proposal - Sujith Kumar Dola

### ISSUE THREAD

**Issue by Sujithkumardola** [codedex-io/projects#14]
1. Hello World Flask App - Beginner
2. Telegram Bot with Python - Intermediate
3. ISS [ International Space Station]  Tracker with Python - Beginner
4.  Ethereum Wallet With Python - Beginner

**Comment by sonnynomnom** [comment]
Let's do the ISS one!!! 🛰

Can you write the final solution code first before writing the tutorial? cc @Bobliuuu @asiqurrahman

**Comment by Sujithkumardola** [comment]
Hey @sonnynomnom, Do you prefer the console version or a GUI version?

**Comment by sonnynomnom** [comment]
Whichever you think you are more comfortable in!

**Comment by Sujithkumardola** [comment]
> Whichever you think you are more comfortable in!

Here's The Gist: https://gist.github.com/Sujithkumardola/bc203083e9ec0c7e8cc3e41833d02e59

**Comment by sonnynomnom** [comment]
Reviewed!

**Comment by Sujithkumardola** [comment]
> Reviewed!

Can I start writing the tutorial?

**Comment by Bobliuuu** [comment]
@Sujithkumardola Yep! Just make sure to apply the changes to your solution code highlighted by the team, and make sure to follow the formatting guide 😄

**Comment by Sujithkumardola** [comment]
@sonnynomnom Take a Look at This Gist : https://gist.github.com/Sujithkumardola/e49cf45a247f6fb1968de7c5bbf6b872

### Details

This Version Uses :

- Flask
- Folium
- ARC GIS


### Screenshots

![127-0-0-1-5000](https://user-images.githubusercontent.com/47243708/199166535-ac7af298-1982-4ef8-9ba5-d13295831701.png)
![127-0-0-1-5000-2](https://user-images.githubusercontent.com/47243708/199166682-60558c1b-9206-41e5-be52-382e217c2f10.png)

CC @Bobliuuu

**Comment by asiqurrahman** [comment]
@Sujithkumardola 

Everyone on the team loves this project! It's come a really long way from where it started.

**Two notes:**
- Can you change the icon to a satellite or a blinking gif to show that it's live
- Can you add a dotted line behind the icon of where it's already been(past 30 minutes or so)? We think this would take the project to the next level!

**Comment by Sujithkumardola** [comment]
> @Sujithkumardola 
> 
> Everyone on the team loves this project! It's come a really long way from where it started.
> 
> **Two notes:**
> - Can you change the icon to a satellite or a blinking gif to show that it's live
> - Can you add a dotted line behind the icon of where it's already been(past 30 minutes or so)? We think this would take the project to the next level!

Yeah, I'll try

**Comment by Sujithkumardola** [comment]
> > @Sujithkumardola 
> > 
> > Everyone on the team loves this project! It's come a really long way from where it started.
> > 
> > **Two notes:**
> > - Can you change the icon to a satellite or a blinking gif to show that it's live
> > - Can you add a dotted line behind the icon of where it's already been(past 30 minutes or so)? We think this would take the project to the next level!
> 
> Yeah, I'll try

Hey Guys,

I've been busy in over the last few weeks.

Folium now supports V6 FA icons as a result of my recent PR. But for this project, let's use V4.

Showing the ISS's path is not a big deal, but explaining it will be quite difficult due to the astronomy material involved.

Suggest me an Icon from FA V4 instead of the satellite Icon from V6. A1

**Comment by Bobliuuu** [comment]
Hi @Sujithkumardola, can we use V6 for this project? There are a lot more icons in V6, so the satellite icon would be best for this project. 
Don't worry about showing the path if it's too complicated. 
How is the project tutorial coming along?

**Comment by Sujithkumardola** [comment]
> Hi @Sujithkumardola, can we use V6 for this project? There are a lot more icons in V6, so the satellite icon would be best for this project. 
> Don't worry about showing the path if it's too complicated. 
> How is the project tutorial coming along? 

The tutorial is coming very well Except it's on paper.

**Comment by Bobliuuu** [comment]
Hey Sujith, what do you mean it's on paper?

**Comment by Bobliuuu** [comment]
Hey @Sujithkumardola, any updates on this project?
